[workspace]
members = [
    "crates/uuidx-core",
    "crates/uuidx-cli",
    "crates/uuidx-wasm",
    "crates/uuidx-ffi",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Nazumeki/uuidx"

[workspace.dependencies]
uuidx-core = { version = "0.1.0", path = "crates/uuidx-core" }

[profile.release]
codegen-units = 1
debug = false
lto = "thin"
opt-level = 3
panic = "abort"
strip = "symbols"
